import { APP_CONSTANTS } from '../constants/app';

export const AppConfig = {
  // Audio Settings
  AUDIO_DEFAULT_VOLUME: 0.5,
  AUDIO_CROSSFADE_DURATION: APP_CONSTANTS.AUDIO_CROSSFADE_DURATION,
  
  // Health Settings
  HEALTH_SYNC_INTERVAL: APP_CONSTANTS.HEALTH_SYNC_INTERVAL,
  
  // Notification Settings
  NOTIFICATION_CHECK_INTERVAL: APP_CONSTANTS.NOTIFICATION_CHECK_INTERVAL,
  
  // Session Settings
  MIN_SESSION_DURATION: APP_CONSTANTS.MIN_SESSION_DURATION,
  MAX_SESSION_DURATION: APP_CONSTANTS.MAX_SESSION_DURATION,
  DEFAULT_SESSION_DURATION: APP_CONSTANTS.DEFAULT_SESSION_DURATION,
};
