import path from "node:path";
import { mkdir, copyFile, writeFile } from "node:fs/promises";
import { Colors } from "../../mobile/src/constants/theme";
import { existsSync } from "node:fs";

interface CopySpec {
  from: string;
  to: string;
}

async function safeCopy({ from, to }: CopySpec) {
  if (!existsSync(from)) throw new Error(`Missing source asset: ${from}`);
  await mkdir(path.dirname(to), { recursive: true });
  await copyFile(from, to);
}

export async function syncPublicAssets() {
  const appRoot = path.resolve(import.meta.dir, "..");
  const repoRoot = path.resolve(appRoot, "../..");

  const publicRoot = path.resolve(appRoot, "public");

  for (const font of ["poppins/Poppins-Regular.ttf", "poppins/Poppins-Medium.ttf", "poppins/Poppins-SemiBold.ttf", "poppins/Poppins-Bold.ttf", "dm-serif-display/DMSerifDisplay-Regular.ttf"]) {
    await safeCopy({
      from: path.resolve(repoRoot, "apps/mobile/assets/fonts", font),
      to: path.resolve(publicRoot, "fonts", path.basename(font)),
    });
  }
  // Generated from mobile tokens; runtime applications remain independent.
  await writeFile(path.resolve(appRoot, "src/mobile-theme.css"), `/* Generated by sync-public-assets.ts. */
:root {
  --recalibra-background: ${Colors.background};
  --recalibra-card: ${Colors.backgroundCard};
  --recalibra-primary: ${Colors.primary};
  --recalibra-primary-light: ${Colors.primaryLight};
  --recalibra-text: ${Colors.textPrimary};
  --recalibra-secondary: ${Colors.textSecondary};
  --recalibra-muted: ${Colors.textMuted};
}
`);

  await safeCopy({
    from: path.resolve(repoRoot, "apps/mobile/assets/logo.svg"),
    to: path.resolve(publicRoot, "brand/logo.svg"),
  });

  await safeCopy({
    from: path.resolve(repoRoot, "apps/mobile/assets/icon.png"),
    to: path.resolve(publicRoot, "brand/icon.png"),
  });
}

await syncPublicAssets();
